feat(validation): write sign up validation
emp-daisy/HelloBooksLib pull request #17
Opened 2019-05-31 10:46 UTC by PelumiAlesh

### What does this PR do?
Add validation to the sign up endpoint
#### Description of Task to be completed?
When a user tries to sign up with the wrong or unsupported input format, the user should receive descriptive signup/Registration validation error(s)
#### How should this be manually tested?
>- Clone the repo
>- Run `npm run dev`
>-  Make a `POST` request with bad input format to localhost:6000/api/v1/auth/signup
#### Any background context you want to provide?
No
#### What are the relevant pivotal tracker stories?
[#166265842](https://www.pivotaltracker.com/story/show/166265842)
#### Screenshots (if appropriate)
![Screenshot 2019-05-31 at 11 41 25 AM](https://user-images.githubusercontent.com/29557902/58700962-840a1900-8399-11e9-8b7c-b9dc308cb1c9.png)
#### Questions:

2019-05-31 10:50 UTC, Hadeneekeh approved these changes

2019-05-31 10:51 UTC, cvjude approved these changes

2019-05-31 10:51 UTC, chuxmykel approved these changes
LGTM

2019-05-31 13:07 UTC, OvieMudi approved these changes

2019-06-01 16:16 UTC, OvieMudi requested changes
All looks all good. Just change your PR header/title to follow the convention.

2019-06-01 18:58 UTC, closed without merging