#166265842 sign-up validation
emp-daisy/HelloBooksLib pull request #18
Opened 2019-05-31 17:42 UTC by PelumiAlesh

### What does this PR do?
Add validation to the sign-up endpoint
#### Description of Task to be completed?
When a user tries to sign up with the wrong or unsupported input format, the user should receive descriptive signup/Registration validation error(s)
#### How should this be manually tested?
>- Clone the repo
>- Run `npm run dev`
>-  Make a `POST` request with bad input format to localhost:6000/api/v1/auth/signup
#### Any background context you want to provide?
No
#### What are the relevant pivotal tracker stories?
[#166265842](https://www.pivotaltracker.com/story/show/166265842)
#### Screenshots (if appropriate)
![Screenshot 2019-05-31 at 11 41 25 AM](https://user-images.githubusercontent.com/29557902/58700962-840a1900-8399-11e9-8b7c-b9dc308cb1c9.png)
#### Questions:

2019-05-31 18:12 UTC, ocranbillions submitted a review, later dismissed

2019-05-31 18:17 UTC, chuxmykel submitted a review, later dismissed
Check the title of that it block and you're good to go

2019-05-31 18:17 UTC, chuxmykel commented on server/__test__/test.spec.js
> +  it('Should reigister a user when all required input is supplied', async (done) => {
I'm sure this isn't supposed to be the title of this `it` block.

2019-06-02 13:54 UTC, Hadeneekeh submitted a review, later dismissed

2019-06-02 17:46 UTC, ocranbillions submitted a review, later dismissed
Handle the merge conflicts and its good to go.

2019-06-02 19:35 UTC, chuxmykel submitted a review, later dismissed
Work on merge conflict and you're good to go.

2019-06-03 07:18 UTC, encodedBicoding reviewed
Gone through the work, it is good. Just needs to fix merge conflicts.

2019-06-03 10:18 UTC, OvieMudi submitted a review, later dismissed

2019-06-03 11:38 UTC, encodedBicoding requested changes
Why is travis failing?

2019-06-03 11:40 UTC, encodedBicoding reviewed
that sequelize table issh is causing build to fail. Are you using postgresDB or elephant?.

2019-06-03 11:43 UTC, PelumiAlesh commented
> that sequelize table issh is causing build to fail. Are you using postgresDB or elephant?.

Im using postgresDB

2019-06-03 13:03 UTC, emp-daisy commented
Why is this still pending?

2019-06-03 13:24 UTC, PelumiAlesh commented
THIS IS THE OLD BRANCH

2019-06-03 13:24 UTC, closed without merging